# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property.
include:
  - board: nice_nano/nrf52840/zmk
    shield: 42block
    artifact-name: 42block
  - board: nice_nano/nrf52840/zmk
    shield: portajohn
    artifact-name: portajohn
  - board: nice_nano/nrf52840/zmk
    shield: ironhorse
    artifact-name: ironhorse
