# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property.
include:
  - board: nice_nano/nrf52840/zmk
    shield: 42block
    artifact-name: 42block
    cmake-args: "-DCONFIG_BT_DEVICE_NAME='\\\"42block\\\"' -DCONFIG_ZMK_KEYBOARD_NAME='\\\"42block\\\"'"
  - board: nice_nano/nrf52840/zmk
    shield: 42block
    artifact-name: portajohn
    cmake-args: "-DCONFIG_BT_DEVICE_NAME='\\\"portajohn\\\"' -DCONFIG_ZMK_KEYBOARD_NAME='\\\"portajohn\\\"'"
  - board: nice_nano/nrf52840/zmk
    shield: 42block
    artifact-name: ironhorse
    cmake-args: "-DCONFIG_BT_DEVICE_NAME='\\\"ironhorse\\\"' -DCONFIG_ZMK_KEYBOARD_NAME='\\\"ironhorse\\\"'"
